// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZ-hZCexX17C4X-3My-QY-zHvPLlclok',
    appId: '1:962459506516:web:d7b71d5aeaab0aad151ac1',
    messagingSenderId: '962459506516',
    projectId: 'employee-attendance-monitoring',
    authDomain: 'employee-attendance-monitoring.firebaseapp.com',
    databaseURL: 'https://employee-attendance-monitoring-default-rtdb.firebaseio.com',
    storageBucket: 'employee-attendance-monitoring.appspot.com',
    measurementId: 'G-ZES2H1PR6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkuAobIMto-3wbCxOP0DA9ESuVSzKnTk8',
    appId: '1:962459506516:android:81f463c2ded01bb3151ac1',
    messagingSenderId: '962459506516',
    projectId: 'employee-attendance-monitoring',
    databaseURL: 'https://employee-attendance-monitoring-default-rtdb.firebaseio.com',
    storageBucket: 'employee-attendance-monitoring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvH0KGnnbTx0XuoK2spPNQHwBXeKG1Bdw',
    appId: '1:962459506516:ios:dd02aea01a1a5cd3151ac1',
    messagingSenderId: '962459506516',
    projectId: 'employee-attendance-monitoring',
    databaseURL: 'https://employee-attendance-monitoring-default-rtdb.firebaseio.com',
    storageBucket: 'employee-attendance-monitoring.appspot.com',
    iosClientId: '962459506516-b43gsfhkhj6ulss57ecotpdkkh15oksc.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualEmp',
  );
}
